server:
  port: 8181

logging:
  level:
    com.straumann: DEBUG

spring:  
  application:
    name: patient-service
  
  profiles:
    active:
      ${SPRING_PROFILES_ACTIVE}
      
spring:
  data:
    mongodb:
      database: patientDB
      auto-index-creation: true
      uri: ${DATABASE_URI}

